-- Primary keys are UUIDv7 generated by the application: time-ordered (B-tree
-- inserts stay append-mostly, ids double as a stable pagination cursor) and
-- not enumerable across tenants the way a bigserial would be.

CREATE TABLE businesses (
    id          uuid PRIMARY KEY,
    name        text        NOT NULL CHECK (length(name) BETWEEN 1 AND 200),
    created_at  timestamptz NOT NULL DEFAULT now()
);

-- Only a SHA-256 of the key is stored. Keys are 256 bits of CSPRNG output,
-- so a fast hash is sufficient (nothing to brute-force) and lets us look the
-- key up by its hash directly instead of scanning + comparing.
CREATE TABLE api_keys (
    id              uuid PRIMARY KEY,
    business_id     uuid        NOT NULL REFERENCES businesses (id),
    key_hash        bytea       NOT NULL UNIQUE CHECK (length(key_hash) = 32),
    display_prefix  text        NOT NULL,
    created_at      timestamptz NOT NULL DEFAULT now(),
    revoked_at      timestamptz
);

CREATE INDEX api_keys_business_idx ON api_keys (business_id);
